# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UnitTest++
email: 
description: > # this means to ignore newlines until "baseurl:"
  A lightweight unit testing framework for C++.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unittest-cpp.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  unittest-cpp

# Build settings
markdown: kramdown
exclude: [vendor]
